//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the regulated_pure_pursuit_controller package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __regulated_pure_pursuit_controller__REGULATEDPUREPURSUITCONTROLLERCONFIG_H__
#define __regulated_pure_pursuit_controller__REGULATEDPUREPURSUITCONTROLLERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace regulated_pure_pursuit_controller
{
  class RegulatedPurePursuitControllerConfigStatics;

  class RegulatedPurePursuitControllerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(RegulatedPurePursuitControllerConfig &config, const RegulatedPurePursuitControllerConfig &max, const RegulatedPurePursuitControllerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const RegulatedPurePursuitControllerConfig &config1, const RegulatedPurePursuitControllerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, RegulatedPurePursuitControllerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const RegulatedPurePursuitControllerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RegulatedPurePursuitControllerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const RegulatedPurePursuitControllerConfig &config) const = 0;
      virtual void getValue(const RegulatedPurePursuitControllerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T RegulatedPurePursuitControllerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T RegulatedPurePursuitControllerConfig::* field;

      virtual void clamp(RegulatedPurePursuitControllerConfig &config, const RegulatedPurePursuitControllerConfig &max, const RegulatedPurePursuitControllerConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const RegulatedPurePursuitControllerConfig &config1, const RegulatedPurePursuitControllerConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, RegulatedPurePursuitControllerConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const RegulatedPurePursuitControllerConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RegulatedPurePursuitControllerConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const RegulatedPurePursuitControllerConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const RegulatedPurePursuitControllerConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, RegulatedPurePursuitControllerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, RegulatedPurePursuitControllerConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(RegulatedPurePursuitControllerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class ROBOT
{
  public:
    ROBOT()
    {
      state = true;
      name = "Robot";
    }

    void setParams(RegulatedPurePursuitControllerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("acc_lim_linear"==(*_i)->name){acc_lim_linear = boost::any_cast<double>(val);}
        if("min_vel_linear"==(*_i)->name){min_vel_linear = boost::any_cast<double>(val);}
        if("max_vel_linear"==(*_i)->name){max_vel_linear = boost::any_cast<double>(val);}
        if("acc_lim_angular"==(*_i)->name){acc_lim_angular = boost::any_cast<double>(val);}
        if("min_vel_angular"==(*_i)->name){min_vel_angular = boost::any_cast<double>(val);}
        if("max_vel_angular"==(*_i)->name){max_vel_angular = boost::any_cast<double>(val);}
        if("is_omnidirectional"==(*_i)->name){is_omnidirectional = boost::any_cast<bool>(val);}
        if("follow_viapoint_orientation"==(*_i)->name){follow_viapoint_orientation = boost::any_cast<bool>(val);}
        if("use_rotate_to_heading"==(*_i)->name){use_rotate_to_heading = boost::any_cast<bool>(val);}
        if("rotate_to_heading_angular_vel"==(*_i)->name){rotate_to_heading_angular_vel = boost::any_cast<double>(val);}
      }
    }

    double acc_lim_linear;
double min_vel_linear;
double max_vel_linear;
double acc_lim_angular;
double min_vel_angular;
double max_vel_angular;
bool is_omnidirectional;
bool follow_viapoint_orientation;
bool use_rotate_to_heading;
double rotate_to_heading_angular_vel;

    bool state;
    std::string name;

    
}robot;

class GOAL
{
  public:
    GOAL()
    {
      state = true;
      name = "Goal";
    }

    void setParams(RegulatedPurePursuitControllerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("xy_goal_tolerance"==(*_i)->name){xy_goal_tolerance = boost::any_cast<double>(val);}
        if("yaw_goal_tolerance"==(*_i)->name){yaw_goal_tolerance = boost::any_cast<double>(val);}
      }
    }

    double xy_goal_tolerance;
double yaw_goal_tolerance;

    bool state;
    std::string name;

    
}goal;

class REGULATEDPUREPURSUIT
{
  public:
    REGULATEDPUREPURSUIT()
    {
      state = true;
      name = "RegulatedPurePursuit";
    }

    void setParams(RegulatedPurePursuitControllerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("use_velocity_scaled_lookahead_dist"==(*_i)->name){use_velocity_scaled_lookahead_dist = boost::any_cast<bool>(val);}
        if("lookahead_dist"==(*_i)->name){lookahead_dist = boost::any_cast<double>(val);}
        if("min_lookahead_dist"==(*_i)->name){min_lookahead_dist = boost::any_cast<double>(val);}
        if("max_lookahead_dist"==(*_i)->name){max_lookahead_dist = boost::any_cast<double>(val);}
        if("lookahead_time"==(*_i)->name){lookahead_time = boost::any_cast<double>(val);}
        if("use_curvature_heuristic"==(*_i)->name){use_curvature_heuristic = boost::any_cast<bool>(val);}
        if("curvature_gain"==(*_i)->name){curvature_gain = boost::any_cast<double>(val);}
        if("curvature_threshold"==(*_i)->name){curvature_threshold = boost::any_cast<double>(val);}
        if("use_proximity_heuristic"==(*_i)->name){use_proximity_heuristic = boost::any_cast<bool>(val);}
        if("proximity_gain"==(*_i)->name){proximity_gain = boost::any_cast<double>(val);}
        if("proximity_threshold"==(*_i)->name){proximity_threshold = boost::any_cast<double>(val);}
        if("transform_tolerance"==(*_i)->name){transform_tolerance = boost::any_cast<double>(val);}
      }
    }

    bool use_velocity_scaled_lookahead_dist;
double lookahead_dist;
double min_lookahead_dist;
double max_lookahead_dist;
double lookahead_time;
bool use_curvature_heuristic;
double curvature_gain;
double curvature_threshold;
bool use_proximity_heuristic;
double proximity_gain;
double proximity_threshold;
double transform_tolerance;

    bool state;
    std::string name;

    
}regulatedpurepursuit;

}groups;



//#line 9 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double acc_lim_linear;
//#line 10 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double min_vel_linear;
//#line 11 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double max_vel_linear;
//#line 13 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double acc_lim_angular;
//#line 14 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double min_vel_angular;
//#line 15 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double max_vel_angular;
//#line 17 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      bool is_omnidirectional;
//#line 18 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      bool follow_viapoint_orientation;
//#line 19 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      bool use_rotate_to_heading;
//#line 20 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double rotate_to_heading_angular_vel;
//#line 24 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double xy_goal_tolerance;
//#line 25 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double yaw_goal_tolerance;
//#line 29 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      bool use_velocity_scaled_lookahead_dist;
//#line 30 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double lookahead_dist;
//#line 31 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double min_lookahead_dist;
//#line 32 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double max_lookahead_dist;
//#line 33 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double lookahead_time;
//#line 35 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      bool use_curvature_heuristic;
//#line 36 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double curvature_gain;
//#line 37 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double curvature_threshold;
//#line 39 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      bool use_proximity_heuristic;
//#line 40 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double proximity_gain;
//#line 41 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double proximity_threshold;
//#line 43 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      double transform_tolerance;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("RegulatedPurePursuitControllerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const RegulatedPurePursuitControllerConfig &__max__ = __getMax__();
      const RegulatedPurePursuitControllerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const RegulatedPurePursuitControllerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const RegulatedPurePursuitControllerConfig &__getDefault__();
    static const RegulatedPurePursuitControllerConfig &__getMax__();
    static const RegulatedPurePursuitControllerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const RegulatedPurePursuitControllerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void RegulatedPurePursuitControllerConfig::ParamDescription<std::string>::clamp(RegulatedPurePursuitControllerConfig &config, const RegulatedPurePursuitControllerConfig &max, const RegulatedPurePursuitControllerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class RegulatedPurePursuitControllerConfigStatics
  {
    friend class RegulatedPurePursuitControllerConfig;

    RegulatedPurePursuitControllerConfigStatics()
    {
RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT, RegulatedPurePursuitControllerConfig> Default("Default", "", 0, 0, true, &RegulatedPurePursuitControllerConfig::groups);
RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::ROBOT, RegulatedPurePursuitControllerConfig::DEFAULT> Robot("Robot", "tab", 0, 1, true, &RegulatedPurePursuitControllerConfig::DEFAULT::robot);
//#line 9 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.acc_lim_linear = 0.0;
//#line 9 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.acc_lim_linear = 20.0;
//#line 9 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.acc_lim_linear = 2.5;
//#line 9 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("acc_lim_linear", "double", 0, "The linear acceleration limit of the robot", "", &RegulatedPurePursuitControllerConfig::acc_lim_linear)));
//#line 9 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("acc_lim_linear", "double", 0, "The linear acceleration limit of the robot", "", &RegulatedPurePursuitControllerConfig::acc_lim_linear)));
//#line 10 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.min_vel_linear = 0.0;
//#line 10 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.min_vel_linear = 20.0;
//#line 10 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.min_vel_linear = 0.1;
//#line 10 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("min_vel_linear", "double", 0, "The minimum linear velocity for the robot in m/s", "", &RegulatedPurePursuitControllerConfig::min_vel_linear)));
//#line 10 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("min_vel_linear", "double", 0, "The minimum linear velocity for the robot in m/s", "", &RegulatedPurePursuitControllerConfig::min_vel_linear)));
//#line 11 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.max_vel_linear = 0.0;
//#line 11 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.max_vel_linear = 20.0;
//#line 11 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.max_vel_linear = 0.5;
//#line 11 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("max_vel_linear", "double", 0, "The maximum linear velocity for the robot in m/s", "", &RegulatedPurePursuitControllerConfig::max_vel_linear)));
//#line 11 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("max_vel_linear", "double", 0, "The maximum linear velocity for the robot in m/s", "", &RegulatedPurePursuitControllerConfig::max_vel_linear)));
//#line 13 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.acc_lim_angular = 0.0;
//#line 13 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.acc_lim_angular = 20.0;
//#line 13 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.acc_lim_angular = 3.2;
//#line 13 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("acc_lim_angular", "double", 0, "The angular acceleration limit of the robot", "", &RegulatedPurePursuitControllerConfig::acc_lim_angular)));
//#line 13 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("acc_lim_angular", "double", 0, "The angular acceleration limit of the robot", "", &RegulatedPurePursuitControllerConfig::acc_lim_angular)));
//#line 14 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.min_vel_angular = 0.0;
//#line 14 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.min_vel_angular = 20.0;
//#line 14 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.min_vel_angular = 0.2;
//#line 14 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("min_vel_angular", "double", 0, "The minimum angular velocity for the robot in rad/s", "", &RegulatedPurePursuitControllerConfig::min_vel_angular)));
//#line 14 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("min_vel_angular", "double", 0, "The minimum angular velocity for the robot in rad/s", "", &RegulatedPurePursuitControllerConfig::min_vel_angular)));
//#line 15 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.max_vel_angular = 0.0;
//#line 15 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.max_vel_angular = 20.0;
//#line 15 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.max_vel_angular = 1.0;
//#line 15 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("max_vel_angular", "double", 0, "The maximum angular velocity for the robot in rad/s", "", &RegulatedPurePursuitControllerConfig::max_vel_angular)));
//#line 15 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("max_vel_angular", "double", 0, "The maximum angular velocity for the robot in rad/s", "", &RegulatedPurePursuitControllerConfig::max_vel_angular)));
//#line 17 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.is_omnidirectional = 0;
//#line 17 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.is_omnidirectional = 1;
//#line 17 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.is_omnidirectional = 1;
//#line 17 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("is_omnidirectional", "bool", 0, "Whether the robot is omnidirectional or not", "", &RegulatedPurePursuitControllerConfig::is_omnidirectional)));
//#line 17 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("is_omnidirectional", "bool", 0, "Whether the robot is omnidirectional or not", "", &RegulatedPurePursuitControllerConfig::is_omnidirectional)));
//#line 18 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.follow_viapoint_orientation = 0;
//#line 18 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.follow_viapoint_orientation = 1;
//#line 18 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.follow_viapoint_orientation = 1;
//#line 18 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("follow_viapoint_orientation", "bool", 0, "Whether to follow orientation set to the viapoints or a linear blend of current and goal orientation when is_omnidirectional is true", "", &RegulatedPurePursuitControllerConfig::follow_viapoint_orientation)));
//#line 18 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("follow_viapoint_orientation", "bool", 0, "Whether to follow orientation set to the viapoints or a linear blend of current and goal orientation when is_omnidirectional is true", "", &RegulatedPurePursuitControllerConfig::follow_viapoint_orientation)));
//#line 19 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.use_rotate_to_heading = 0;
//#line 19 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.use_rotate_to_heading = 1;
//#line 19 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.use_rotate_to_heading = 1;
//#line 19 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_rotate_to_heading", "bool", 0, "Whether to enable rotating at start and goal when is_omnidirectional is false. Recommended on for all robot types that can rotate in place", "", &RegulatedPurePursuitControllerConfig::use_rotate_to_heading)));
//#line 19 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_rotate_to_heading", "bool", 0, "Whether to enable rotating at start and goal when is_omnidirectional is false. Recommended on for all robot types that can rotate in place", "", &RegulatedPurePursuitControllerConfig::use_rotate_to_heading)));
//#line 20 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.rotate_to_heading_angular_vel = 0.0;
//#line 20 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.rotate_to_heading_angular_vel = 20.0;
//#line 20 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.rotate_to_heading_angular_vel = 0.5;
//#line 20 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Robot.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("rotate_to_heading_angular_vel", "double", 0, "If use_rotate_to_heading is true, this is the angular velocity to use", "", &RegulatedPurePursuitControllerConfig::rotate_to_heading_angular_vel)));
//#line 20 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("rotate_to_heading_angular_vel", "double", 0, "If use_rotate_to_heading is true, this is the angular velocity to use", "", &RegulatedPurePursuitControllerConfig::rotate_to_heading_angular_vel)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Robot.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::ROBOT, RegulatedPurePursuitControllerConfig::DEFAULT>(Robot)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::ROBOT, RegulatedPurePursuitControllerConfig::DEFAULT>(Robot)));
RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::GOAL, RegulatedPurePursuitControllerConfig::DEFAULT> Goal("Goal", "tab", 0, 2, true, &RegulatedPurePursuitControllerConfig::DEFAULT::goal);
//#line 24 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.xy_goal_tolerance = 0.0;
//#line 24 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.xy_goal_tolerance = 2.0;
//#line 24 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.xy_goal_tolerance = 0.25;
//#line 24 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Goal.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "The tolerance in meters for the controller in the x & y distance when achieving a goal", "", &RegulatedPurePursuitControllerConfig::xy_goal_tolerance)));
//#line 24 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "The tolerance in meters for the controller in the x & y distance when achieving a goal", "", &RegulatedPurePursuitControllerConfig::xy_goal_tolerance)));
//#line 25 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.yaw_goal_tolerance = 0.0;
//#line 25 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.yaw_goal_tolerance = 2.0;
//#line 25 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.yaw_goal_tolerance = 0.25;
//#line 25 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      Goal.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "The tolerance in radians for the controller in yaw/rotation when achieving its goal", "", &RegulatedPurePursuitControllerConfig::yaw_goal_tolerance)));
//#line 25 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "The tolerance in radians for the controller in yaw/rotation when achieving its goal", "", &RegulatedPurePursuitControllerConfig::yaw_goal_tolerance)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Goal.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::GOAL, RegulatedPurePursuitControllerConfig::DEFAULT>(Goal)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::GOAL, RegulatedPurePursuitControllerConfig::DEFAULT>(Goal)));
RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::REGULATEDPUREPURSUIT, RegulatedPurePursuitControllerConfig::DEFAULT> RegulatedPurePursuit("RegulatedPurePursuit", "tab", 0, 3, true, &RegulatedPurePursuitControllerConfig::DEFAULT::regulatedpurepursuit);
//#line 29 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.use_velocity_scaled_lookahead_dist = 0;
//#line 29 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.use_velocity_scaled_lookahead_dist = 1;
//#line 29 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.use_velocity_scaled_lookahead_dist = 1;
//#line 29 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_velocity_scaled_lookahead_dist", "bool", 0, "Whether to use the velocity scaled lookahead distances or constant lookahead_distance", "", &RegulatedPurePursuitControllerConfig::use_velocity_scaled_lookahead_dist)));
//#line 29 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_velocity_scaled_lookahead_dist", "bool", 0, "Whether to use the velocity scaled lookahead distances or constant lookahead_distance", "", &RegulatedPurePursuitControllerConfig::use_velocity_scaled_lookahead_dist)));
//#line 30 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.lookahead_dist = 0.0;
//#line 30 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.lookahead_dist = 10.0;
//#line 30 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.lookahead_dist = 0.6;
//#line 30 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("lookahead_dist", "double", 0, "The lookahead distance (m) to use to find the lookahead point when use_velocity_scaled_lookahead_dist is false", "", &RegulatedPurePursuitControllerConfig::lookahead_dist)));
//#line 30 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("lookahead_dist", "double", 0, "The lookahead distance (m) to use to find the lookahead point when use_velocity_scaled_lookahead_dist is false", "", &RegulatedPurePursuitControllerConfig::lookahead_dist)));
//#line 31 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.min_lookahead_dist = 0.0;
//#line 31 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.min_lookahead_dist = 10.0;
//#line 31 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.min_lookahead_dist = 0.3;
//#line 31 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("min_lookahead_dist", "double", 0, "The minimum lookahead distance (m) threshold when use_velocity_scaled_lookahead_dist is true", "", &RegulatedPurePursuitControllerConfig::min_lookahead_dist)));
//#line 31 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("min_lookahead_dist", "double", 0, "The minimum lookahead distance (m) threshold when use_velocity_scaled_lookahead_dist is true", "", &RegulatedPurePursuitControllerConfig::min_lookahead_dist)));
//#line 32 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.max_lookahead_dist = 0.0;
//#line 32 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.max_lookahead_dist = 10.0;
//#line 32 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.max_lookahead_dist = 0.9;
//#line 32 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("max_lookahead_dist", "double", 0, "The maximum lookahead distance (m) threshold when use_velocity_scaled_lookahead_dist is true", "", &RegulatedPurePursuitControllerConfig::max_lookahead_dist)));
//#line 32 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("max_lookahead_dist", "double", 0, "The maximum lookahead distance (m) threshold when use_velocity_scaled_lookahead_dist is true", "", &RegulatedPurePursuitControllerConfig::max_lookahead_dist)));
//#line 33 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.lookahead_time = 0.0;
//#line 33 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.lookahead_time = 10.0;
//#line 33 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.lookahead_time = 1.5;
//#line 33 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("lookahead_time", "double", 0, "The time (s) to project the velocity by when use_velocity_scaled_lookahead_dist is true. Also known as the lookahead gain", "", &RegulatedPurePursuitControllerConfig::lookahead_time)));
//#line 33 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("lookahead_time", "double", 0, "The time (s) to project the velocity by when use_velocity_scaled_lookahead_dist is true. Also known as the lookahead gain", "", &RegulatedPurePursuitControllerConfig::lookahead_time)));
//#line 35 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.use_curvature_heuristic = 0;
//#line 35 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.use_curvature_heuristic = 1;
//#line 35 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.use_curvature_heuristic = 1;
//#line 35 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_curvature_heuristic", "bool", 0, "Whether to use the regulated features for path curvature (e.g. slow on high curvature paths)", "", &RegulatedPurePursuitControllerConfig::use_curvature_heuristic)));
//#line 35 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_curvature_heuristic", "bool", 0, "Whether to use the regulated features for path curvature (e.g. slow on high curvature paths)", "", &RegulatedPurePursuitControllerConfig::use_curvature_heuristic)));
//#line 36 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.curvature_gain = 0.0;
//#line 36 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.curvature_gain = 1.0;
//#line 36 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.curvature_gain = 1.0;
//#line 36 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("curvature_gain", "double", 0, "The gain to use for the curvature heuristic when use_curvature_heuristic is true", "", &RegulatedPurePursuitControllerConfig::curvature_gain)));
//#line 36 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("curvature_gain", "double", 0, "The gain to use for the curvature heuristic when use_curvature_heuristic is true", "", &RegulatedPurePursuitControllerConfig::curvature_gain)));
//#line 37 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.curvature_threshold = 0.0;
//#line 37 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.curvature_threshold = 10.0;
//#line 37 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.curvature_threshold = 1.1;
//#line 37 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("curvature_threshold", "double", 0, "The curvature (1/m) for which the regulation features are triggered when use_curvature_heuristic is true", "", &RegulatedPurePursuitControllerConfig::curvature_threshold)));
//#line 37 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("curvature_threshold", "double", 0, "The curvature (1/m) for which the regulation features are triggered when use_curvature_heuristic is true", "", &RegulatedPurePursuitControllerConfig::curvature_threshold)));
//#line 39 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.use_proximity_heuristic = 0;
//#line 39 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.use_proximity_heuristic = 1;
//#line 39 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.use_proximity_heuristic = 1;
//#line 39 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_proximity_heuristic", "bool", 0, "Whether to use the regulated features for proximity to obstacles (e.g. slow in close proximity to obstacles)", "", &RegulatedPurePursuitControllerConfig::use_proximity_heuristic)));
//#line 39 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<bool>("use_proximity_heuristic", "bool", 0, "Whether to use the regulated features for proximity to obstacles (e.g. slow in close proximity to obstacles)", "", &RegulatedPurePursuitControllerConfig::use_proximity_heuristic)));
//#line 40 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.proximity_gain = 0.0;
//#line 40 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.proximity_gain = 1.0;
//#line 40 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.proximity_gain = 0.5;
//#line 40 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("proximity_gain", "double", 0, "The gain to use for the proximity heuristic when use_proximity_heuristic is true", "", &RegulatedPurePursuitControllerConfig::proximity_gain)));
//#line 40 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("proximity_gain", "double", 0, "The gain to use for the proximity heuristic when use_proximity_heuristic is true", "", &RegulatedPurePursuitControllerConfig::proximity_gain)));
//#line 41 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.proximity_threshold = 0.0;
//#line 41 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.proximity_threshold = 10.0;
//#line 41 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.proximity_threshold = 0.5;
//#line 41 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("proximity_threshold", "double", 0, "The distance (m) to the closest obstacle for which the regulation features are triggered when use_proximity_heuristic is true", "", &RegulatedPurePursuitControllerConfig::proximity_threshold)));
//#line 41 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("proximity_threshold", "double", 0, "The distance (m) to the closest obstacle for which the regulation features are triggered when use_proximity_heuristic is true", "", &RegulatedPurePursuitControllerConfig::proximity_threshold)));
//#line 43 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __min__.transform_tolerance = 0.0;
//#line 43 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __max__.transform_tolerance = 20.0;
//#line 43 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __default__.transform_tolerance = 0.1;
//#line 43 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      RegulatedPurePursuit.abstract_parameters.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("transform_tolerance", "double", 0, "The TF transform tolerance (s)", "", &RegulatedPurePursuitControllerConfig::transform_tolerance)));
//#line 43 "/home/tianbot/catkin_ws/src/submodule/regulated_pure_pursuit_controller/cfg/RegulatedPurePursuitController.cfg"
      __param_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::ParamDescription<double>("transform_tolerance", "double", 0, "The TF transform tolerance (s)", "", &RegulatedPurePursuitControllerConfig::transform_tolerance)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      RegulatedPurePursuit.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::REGULATEDPUREPURSUIT, RegulatedPurePursuitControllerConfig::DEFAULT>(RegulatedPurePursuit)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT::REGULATEDPUREPURSUIT, RegulatedPurePursuitControllerConfig::DEFAULT>(RegulatedPurePursuit)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr(new RegulatedPurePursuitControllerConfig::GroupDescription<RegulatedPurePursuitControllerConfig::DEFAULT, RegulatedPurePursuitControllerConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    RegulatedPurePursuitControllerConfig __max__;
    RegulatedPurePursuitControllerConfig __min__;
    RegulatedPurePursuitControllerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const RegulatedPurePursuitControllerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static RegulatedPurePursuitControllerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &RegulatedPurePursuitControllerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const RegulatedPurePursuitControllerConfig &RegulatedPurePursuitControllerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const RegulatedPurePursuitControllerConfig &RegulatedPurePursuitControllerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const RegulatedPurePursuitControllerConfig &RegulatedPurePursuitControllerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<RegulatedPurePursuitControllerConfig::AbstractParamDescriptionConstPtr> &RegulatedPurePursuitControllerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<RegulatedPurePursuitControllerConfig::AbstractGroupDescriptionConstPtr> &RegulatedPurePursuitControllerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const RegulatedPurePursuitControllerConfigStatics *RegulatedPurePursuitControllerConfig::__get_statics__()
  {
    const static RegulatedPurePursuitControllerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = RegulatedPurePursuitControllerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __REGULATEDPUREPURSUITCONTROLLERRECONFIGURATOR_H__
