regulated_pure_pursuit_controller:
   acc_lim_linear: 2.5 
   min_vel_linear: 0.1 
   max_vel_linear: 0.5 

   acc_lim_angular: 3.2 
   min_vel_angular: 0.2 
   max_vel_angular: 1.0 

   is_omnidirectional: true 
   follow_viapoint_orientation: true 
   use_rotate_to_heading: true 
   rotate_to_heading_angular_vel: 0.5 

   xy_goal_tolerance: 0.25 
   yaw_goal_tolerance: 0.25 

   use_velocity_scaled_lookahead_dist: true 
   lookahead_dist: 0.6 
   min_lookahead_dist: 0.3 
   max_lookahead_dist: 0.9 
   lookahead_time: 1.5 

   use_curvature_heuristic": true 
   curvature_gain: 1.0 
   curvature_threshold: 1.1 

   use_proximity_heuristic: true 
   proximity_gain: 0.5 
   proximity_threshold: 0.5 

   transform_tolerance: 0.1 